name: Gatsby PR Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: deploy
          access-token: ${{ secrets.GITHUB_TOKEN }}
          skip-publish: true
