name: Gatsby Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: deploy
          access-token: ${{ secrets.ACCESS_TOKEN }}
